version: '3.5'

x-rack: &rack
  command: bash -c "bundle exec rake prod_up && bundle exec unicorn -c config/unicorn.rb"
  image: 18xx_rack:prod
  environment:
    RACK_ENV: production
    DATABASE_URL: $DATABASE_URL
    ELASTIC_KEY: $ELASTIC_KEY
    NEW_RELIC_LICENSE_KEY: $NEW_RELIC_LICENSE_KEY
    RUBYOPTS: --jit
    PORT: 9292
  build:
    args:
      RACK_ENV: production
    context: .
  volumes:
    - .:/18xx
  depends_on:
    - db
    - redis
  logging:
    options:
      max-size: "50m"

services:
  rack:
    <<: *rack
    ports:
      - 9292:9292

  rack_backup:
    <<: *rack

  queue:
    <<: *rack
    command: bundle exec ruby queue.rb

  db:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
